[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install libdbus-1-dev:$CROSS_DEB_ARCH libsqlite3-dev:$CROSS_DEB_ARCH"
]                 
[target.armv7-unknown-linux-gnueabihf]
# image = "debian:bookworm"
